# Generated by Django 3.1.1 on 2020-11-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter your name', max_length=20)),
                ('state', models.CharField(help_text='enter your working state', max_length=10)),
                ('dist', models.CharField(help_text='enter your working district', max_length=20)),
                ('phone', models.IntegerField(help_text='enter your contact no.')),
                ('pincode', models.IntegerField(help_text='enter your pin code')),
                ('experience', models.FloatField(help_text='enter your work experince in year')),
                ('vehicle', models.CharField(choices=[('car', 'car'), ('bike', 'bike'), ('auto', 'auto')], default='bike', help_text='choose the vehicle u drive', max_length=5)),
                ('fee', models.IntegerField(help_text='how much money(in rupees) you charge for one day')),
            ],
        ),
    ]
