# Generated by Django 3.1.1 on 2020-11-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_servant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home_servant',
            new_name='servant',
        ),
    ]
