# Generated by Django 3.1.1 on 2020-11-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carpenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('dist', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('experience', models.FloatField()),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
