# Generated by Django 3.1.1 on 2020-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
